name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
    - name: install Android tooling
      run: sudo apt-get install android-tools-adb openjdk-8-jdk
    - name: generate android keystore
      run: keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12 && cp debug.keystore /tmp/debug.keystore
    - name: checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
    - name: copy editor settings
      run: mkdir -p ~/.config/godot && cp /home/runner/work/Kvalfors/Kvalfors/.github/config/editor_settings-3.tres ~/.config/godot/editor_settings-3.tres
    - name: get tag from version
      id: tag_version
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}
    - name: export game
      uses: firebelley/godot-export@v2.6.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_export_templates.tpz
        relative_project_path: ./
        create_release: true
        base_version:  ${{ steps.tag_version.outputs.TAG_VERSION}} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LANG: en
