name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
    - name: install android tooling
      run: sudo apt-get install android-tools-adb openjdk-8-jdk
    - name: checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
    - name: get tag from version
      id: tag_version
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}
    - name: export game
      uses: firebelley/godot-export@v2.6.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_export_templates.tpz
        relative_project_path: ./
        create_release: false
        base_version:  ${{ steps.tag_version.outputs.TAG_VERSION}} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
